# docker-compose.yml

version: '3.3'    
services:
  occupant_model_service:
    build:
      context: ../
      dockerfile: cosim/Dockerfile
    networks:
      - alfalfa_default
networks:
  alfalfa_default:
    external: true
